name: permission_config
description: A Flutter CLI plugin that auto-adds Android/iOS permissions and generates permission handler logic.
version: 0.0.2

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  path: ^1.9.0
  xml: ^6.5.0
  logger: ^2.0.2

executables:
  permission_config: permission_config

repository: https://github.com/jassimpv/permissions_config
issue_tracker: https://github.com/jassimpv/permissions_config/issues
